apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app1
  labels:
    app: sample-python-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python-app1
  template:
    metadata:
      labels:
        app: sample-python-app1
    spec:
      containers:
        - name: python-app
          image: sample-python-app 
          ports:
            - containerPort: 8000
                                                                                                                              
